# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    paths-ignore:
      - 'bootstrap/**'
      - 'dist/**'
    branches: [ "testci" ]
  pull_request:
    branches: [ "testci" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js CI ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './code/job-portal-vue3/package-lock.json'
    - run: npm ci
      working-directory: ./code/job-portal-vue3/
    - run: npm run build --if-present
      working-directory: ./code/job-portal-vue3/
    
    # Run unit test npm run test:unit
   - name: Deploy to Firebase Hosting
     uses: w9jds/firebase-action@v1.4.0
     with:
       args: deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
     env:
      FIREBASE_CLI_LOGIN: ${{ secrets.FIREBASE_CLI_LOGIN }}
