name: Firebase Deploy

on:
  push:
    branches:
      - testci # Change this to your main branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can change this to the desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the Vue.js app
        run: npm run build

      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
